name: romantic_poetry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  share_plus: ^11.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  get: ^4.7.2
  google_mobile_ads: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  get_cli: ^1.9.1
  http: ^1.4.0
  google_fonts: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

# 🔹 Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_logo.png"
